### ISSUE TITLE
linux ftp  No route to host

### ISSUE THREAD

**Issue by Heipiao** [mikecroucher/Intro_to_HPC#12]
I use computer at diamond, I want to use ftp to upload file to sharc. but I find that
`
act16sl@ltsp1022:~$ ftp sharc.shef.ac.uk
ftp: connect: No route to host
`
i want to know why?
thank you !

**Comment by mikecroucher** [comment]
You cannot use ftp. I suggest that you use MobaXTerm as we discussed in the tutorial.

I'd usually suggest using `scp` but have no idea if that's installed in diamond or not.
