### ISSUE TITLE
Your "qrsh" request could not be scheduled, try again later.

### ISSUE THREAD

**Issue by Heipiao** [mikecroucher/Intro_to_HPC#14]
when I want use GPU in HPC,  ` qrshx -l gpu=1 -l mem=8G`
it alway show this since two days, when I remove gpu=1 , it is fine.
I want to know why ?thank you.

**Comment by mikecroucher** [comment]
There are not many GPUs available in the general pool. 
Since you have access to the RSE queue, you have access to a few more GPUs than 'normal' people.
Try this

`qrshx -l gpu=1 -l mem=8G -P rse`

If it still doesn't work, its just because there are not enough GPUs in the system.
